### PR TITLE
export NAME, VERSION, and ARCH before running linuxdeploy

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by andy5995** [comment]
@probonopd Do you know why exporting NAME in this PR didn't work?

**Comment by StanleySweet** [comment]
Have you tried build other arches like aarch64 or powerpc64le?

**Comment by andy5995** [comment]
> Have you tried build other arches like aarch64 or powerpc64le?

Not yet. It doesn't look like other arches are available on GitHub runners https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

**Comment by andy5995** [comment]
> > Have you tried build other arches like aarch64 or powerpc64le?

@StanleySweet Though it could be done easily enough with a github self-hosted runner.

https://amperecomputing.com/blogs/2022-07-21/adding-aarch64-to-your-github-ci-with-github-actions-and-ampere-altra.html

 Are there any WFG servers that have those architectures?

**Comment by StanleySweet** [comment]
Unfortunately, we do not. There is only one server on good old x64

**Comment by andy5995** [comment]
> Unfortunately, we do not. There is only one server on good old x64

@StanleySweet I think it could be done with the [docker qemu action](https://github.com/docker/setup-qemu-action)

**Comment by andy5995** [comment]
@StanleySweet Locally, if you run `docker run --rm --privileged tonistiigi/binfmt --install all` (https://github.com/tonistiigi/binfmt)

Then you can get an arm64 image, for example, `docker run -it --rm --platform arm64 ubuntu:jammy`

Will get you an arm64 image...

**Comment by StanleySweet** [comment]
Interesting. Sorry I didn't make any progress on getting this on the CI....

**Comment by andy5995** [comment]
@StanleySweet No worries. If it becomes a problem for me to maintain, I'll just pause.

If you want to take a shortcut, you can just clone this repo onto one of your servers that has docker installed, and then run `./make-appimage.sh'. It'll spit out a nice official AppImage for you. :) The brief instructions are on the README.

Alternatively, you can click the "use this template" button near the top of the repo. That will give you a "detached" fork, and then it's all yours to do with as you please.

**Comment by andy5995** [comment]
I am close to trying a build on arm64 and arm/v7 in https://github.com/0ad-matters/0ad-appimage/pull/26 but I may only try with the next official pre-release of 0ad, because I've had too much trouble getting a26 to build with Ubuntu Focal.

**Comment by andy5995** [comment]
Closed, obsolete PR.

**Comment by andy5995** [comment]
> Have you tried build other arches like aarch64 or powerpc64le?

@StanleySweet Once the amd64 build completes successfully in https://github.com/0ad-matters/0ad-appimage/pull/26#issuecomment-2381130695, I can add 'arm64' to the workflow matrix

**Pull request closed without merging**
